### ISSUE TITLE
Release and publish

### ISSUE THREAD

**Issue by PawelJ-PL** [dobrynya/zio-jms#1]
The library looks promising. Are you planning to publish it on the Maven Central?

**Comment by dobrynya** [comment]
At this very moment it's not production ready. I need some time to complete
the work and then to publish to the repo.


чт, 17 сент. 2020 г., 00:25 PawelJ-PL <notifications@github.com>:

**Comment by dobrynya** [comment]
@PawelJ-PL Hi Pawel
I've published this library to Bintray repo. Please take a look at README.
